version: 2.1

jobs:
  greetings:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
        command: echo "Bem vindo ao CircleCI!"

workflows:
  hello-world:
    jobs: 
      - greetings